### PR TITLE
Fix groupreduce with var and std for Unitful types

### LINKED ISSUE #2600: combine() error with std() on GroupedDataFrame with Unitful columns
```
using DataFrames, Statistics, Unitful
df = DataFrame(a=[:a, :a, :b, :b], b=[0, 1, 2, 3]u"m")
```

```
julia> combine(df, :b => std)
1×1 DataFrame
 Row │ b_std
     │ Quantity…
─────┼───────────
   1 │ 1.29099 m
```

```
julia> combine(groupby(df, :a), :b => std)
ERROR: DimensionError: 0.0 m and 0.25 m² are not dimensionally compatible.
Stacktrace:
 [1] +(::Quantity{Float64,𝐋,Unitful.FreeUnits{(m,),𝐋,nothing}}, ::Quantity{Float64,𝐋²,Unitful.FreeUnits{(m²,),𝐋²,nothing}}) at /Users/tomyun/.julia/packages/Unitful/1t88N/src/quantities.jl:137
 [2] groupreduce!(::Array{Quantity{Float64,𝐋,Unitful.FreeUnits{(m,),𝐋,nothing}},1}, ::DataFrames.var"#535#538"{Array{Quantity{Float64,𝐋,Unitful.FreeUnits{(m,),𝐋,nothing}},1}}, ::typeof(+), ::Nothing, ::Function, ::Bool, ::Array{Quantity{Int64,𝐋,Unitful.FreeUnits{(m,),𝐋,nothing}},1}, ::GroupedDataFrame{DataFrame}) at /Users/tomyun/.julia/packages/DataFrames/yqToF/src/groupeddataframe/fastaggregates.jl:174
 [3] (::DataFrames.Aggregate{typeof(var),Nothing})(::Array{Quantity{Int64,𝐋,Unitful.FreeUnits{(m,),𝐋,nothing}},1}, ::GroupedDataFrame{DataFrame}) at /Users/tomyun/.julia/packages/DataFrames/yqToF/src/groupeddataframe/fastaggregates.jl:248
 [4] (::DataFrames.Aggregate{typeof(std),Nothing})(::Array{Quantity{Int64,𝐋,Unitful.FreeUnits{(m,),𝐋,nothing}},1}, ::GroupedDataFrame{DataFrame}) at /Users/tomyun/.julia/packages/DataFrames/yqToF/src/groupeddataframe/fastaggregates.jl:254
 [5] _combine_process_agg(::Pair{Int64,var"#s151"} where var"#s151"<:(Pair{var"#s150",Symbol} where var"#s150"<:Function), ::Bool, ::DataFrame, ::GroupedDataFrame{DataFrame}, ::Dict{Symbol,Tuple{Bool,Int64}}, ::Array{DataFrames.TransformationResult,1}, ::Array{Int64,1}) at /Users/tomyun/.julia/packages/DataFrames/yqToF/src/groupeddataframe/splitapplycombine.jl:203
 [6] _combine(::GroupedDataFrame{DataFrame}, ::Array{Any,1}, ::Array{Bool,1}, ::Bool, ::Bool, ::Bool) at /Users/tomyun/.julia/packages/DataFrames/yqToF/src/groupeddataframe/splitapplycombine.jl:532
 [7] _combine_prepare(::GroupedDataFrame{DataFrame}, ::Union{Regex, AbstractString, Function, Signed, Symbol, Unsigned, Pair, AbstractArray{T,1} where T, Type, All, Between, Cols, InvertedIndex}; keepkeys::Bool, ungroup::Bool, copycols::Bool, keeprows::Bool, renamecols::Bool) at /Users/tomyun/.julia/packages/DataFrames/yqToF/src/groupeddataframe/splitapplycombine.jl:66
 [8] #combine#509 at /Users/tomyun/.julia/packages/DataFrames/yqToF/src/groupeddataframe/splitapplycombine.jl:638 [inlined]
 [9] combine(::GroupedDataFrame{DataFrame}, ::Pair{Symbol,typeof(std)}) at /Users/tomyun/.julia/packages/DataFrames/yqToF/src/groupeddataframe/splitapplycombine.jl:638
 [10] top-level scope at REPL[16]:1
```

Tested on Julia 1.5.3 with DataFrames 0.22.2 and Unitful 1.5.0.

### PR DESCRIPTION
**Pull request by nalimilan**
For `Number`s for which squaring changes the type, we need to use different types for the mean, the variance and the standard deviation.

Fixes #2600.

@bkamins Do you think we should add Unitful as a test dependency to test this? I wonder whether there are types in Base that would allow reproducing the problem. Otherwise we could create a custom type just for this.

### CODE REVIEW

**Comment by bkamins** [comment]
I think adding Unitful.jl as [extras] dependency is not a problem.

File: src/groupeddataframe/fastaggregates.jl [hunk 1]
```diff
@@ -238,12 +238,11 @@ end
 
 function (agg::Aggregate{typeof(var)})(incol::AbstractVector, gd::GroupedDataFrame)
     means = groupreduce((x, i) -> x, Base.add_sum, agg.condf, /, false, incol, gd)
+    z = zero(eltype(incol))
```
Comment (bkamins) [inline src/groupeddataframe/fastaggregates.jl:241]: This should be more precise I think:
```suggestion
    z = zero(eltype(incol)) - zero(eltype(means))
```

**Comment by bkamins** [comment]
@nalimilan - when we merge this we should backport it to https://github.com/JuliaData/DataFrames.jl/tree/0.22_patches and make a release. Therefore can you please change the version to 0.22.3 in Project.toml in this PR?

(I can do the backport and the release later, unless you would prefer to do it)

**Comment by bkamins** [comment]
So now we have:
```
m^2 and NaN are not dimensionally compatible.
```
On Julia 1.0 😢.

**Comment by nalimilan** [comment]
Actually that's a legitimate failure that must be fixed on other versions too. The random values just happened to hit that case on Julia 1.0. I've pushed a fix and an adaptation of tests to more reliably cover the situation where a group contains a single row.

File: test/grouping.jl [hunk 2]
```diff
@@ -1,6 +1,7 @@
 module TestGrouping
 
-using Test, DataFrames, Random, Statistics, PooledArrays, CategoricalArrays, DataAPI
+using Test, DataFrames, Random, Statistics, PooledArrays, CategoricalArrays, DataAPI,
```
Comment (bkamins) [inline test/grouping.jl:3]: I would not make a line break here :)

File: test/grouping.jl [hunk 3]
```diff
@@ -904,8 +905,11 @@ Base.isless(::TestType, ::TestType) = false
 @testset "combine with aggregation functions (skipmissing=$skip, sort=$sort, indices=$indices)" for
     skip in (false, true), sort in (false, true), indices in (false, true)
     Random.seed!(1)
-    df = DataFrame(a = rand([1:5;missing], 20), x1 = rand(1:100, 20),
-                   x2 = rand(1:100, 20) +im*rand(1:100, 20))
+    # 5 is there to ensure we test a single-row group
+    df = DataFrame(a = [rand([1:4;missing], 19); 5],
+                   x1 = rand(1:100, 20),
+                   x2 = rand(1:100, 20) + im*rand(1:100, 20),
+                   x4 = rand(1:100, 20) .* u"m")
```
Comment (bkamins) [inline test/grouping.jl:912]: can we also add `x5` column that would be like `x4` but also contain `missing` value and then below, in particular we would test also `var∘skipmissing` etc. (and make sure that we have a group that has only `missing` values in it).

In general I would want to test what happens if fast aggregation functions get a vector of zero length (which is only possible with `missing`s as currently our groups must have a positive length).

**Review by bkamins — APPROVED** [review]
Wow - that was fast and precise. I would just add one more test as commented (hopefully it will pass so I approve the PR).

File: test/grouping.jl (hunk 3 above)
Comment (nalimilan) [reply test/grouping.jl:912]: This is tested below. Do you mean we should also test it for Unitful? I'm afraid that will require duplicating the whole block, as `prod` doesn't apply to these so we can't just loop over different types of columns. And then there's also `Complex` and `CategoricalArray`...

File: test/grouping.jl (hunk 2 above)
Comment (nalimilan) [reply test/grouping.jl:3]: Well without it the line takes 94 chars... :-)

File: test/grouping.jl (hunk 3 above)
Comment (bkamins) [reply test/grouping.jl:912]: Yes - I meant a test with `Unitful`. Maybe then just add a small test with e.g. `var∘skipmissing` on a concrete test DataFrame like: one group only, column is union of missing and `Unitful` and contains only `missing` values?

File: test/grouping.jl (hunk 2 above)
Comment (bkamins) [reply test/grouping.jl:3]: as you like then :)

File: test/grouping.jl (hunk 3 above)
Comment (nalimilan) [reply test/grouping.jl]: OK, let's bite the bullet and add systematic tests like for floats. I've pushed a commit.

File: test/grouping.jl [hunk 4]
```diff
@@ -965,29 +968,95 @@ Base.isless(::TestType, ::TestType) = false
...
+        @test typeof(res.y) == typeof(expected.y)
+        res = combine(gd, :x2m => f∘skipmissing => :y)
+        expected = combine(gd, :x2m => (x -> f(collect(skipmissing(x)))) => :y)
+        @test res ≅ expected
+        @test typeof(res.y) == typeof(expected.y)
+
+        # Test reduction over group with only missing values
+        gd = groupby_checked(df, :a, skipmissing=skip, sort=sort)
+        indices && @test gd.idx !== nothing # Trigger computation of indices
+        gd[1][:, :x2m] .= missing
```
Comment (bkamins) [inline test/grouping.jl:990]: nice 😄

**Review by bkamins — APPROVED** [review]

**Comment by bkamins** [comment]
will you make a patch release or should I do it?

**Comment by nalimilan** [comment]
Please go ahead. :-)
