### PR TITLE
fix AbstractDataFrame docstring

### LINKED ISSUE #1919: Docstring for AbstractDataFrame still reflects old syntax
[See here](https://github.com/JuliaData/DataFrames.jl/blob/445ecd90caa81f0c3e647283734985b50e2f6ae8/src/abstractdataframe/abstractdataframe.jl#L41-L53).

I'd do a PR, but I don't feel I understand the new syntax and how it connects to the abstract type well enough to write anything coherent.

### PR DESCRIPTION
**Pull request by bkamins**
Fixes #1919

### CODE REVIEW

**Comment by kescobo** [comment]
I like this - makes more sense to link to a source of truth rather than duplicating it such that they can get out of sync 👍

**Comment by bkamins** [comment]
@nalimilan - I will hold off with merging this before you have a look at the docs update.

File: src/abstractdataframe/abstractdataframe.jl [hunk 1]
```diff
@@ -38,33 +38,18 @@ The following are normally implemented for AbstractDataFrames:
...
-d[1:3, :colA]
-d[3,3]
-d[3,:]
-d[3,[:colA, :colB]]
-d[:, [:colA, :colB]]
-d[[1:3; 5], :]
-```
+A detailed description of `getindex`, `setindex!`, `getproperty`, `setproperty!`,
+broadcasting and broadcasting assignment for data frames is given in
+https://juliadata.github.io/DataFrames.jl/stable/lib/indexing/.
```
Comment (nalimilan) [inline src/abstractdataframe/abstractdataframe.jl]:
```suggestion
the ["Indexing" section](https://juliadata.github.io/DataFrames.jl/stable/lib/indexing/) of the manual.
```
