### PR TITLE
add disallowmissing, allowmissing and categorical; fix a bug in categorical!

### LINKED ISSUE #1720: Support disallowmissing
One of the things out of the confusion in #1718 
was that we should have a nonmutating `disallowmissing`  that applies to all abstract dataframes,
including `SubDataFrames`

### PR DESCRIPTION
**Pull request by bkamins**
Fixes #1720

To make things consistent I add `disallowmissing`, `allowmissing` and `categorical` support.

I also fix a bug in `categorical!` which incorrectly handled `:` passed as column selector.

### CODE REVIEW

File: src/abstractdataframe/abstractdataframe.jl [hunk 1]
```diff
@@ -1280,3 +1283,168 @@ julia> ncol(df)
 
 """
 (nrow, ncol)
+
+"""
+    disallowmissing(df::AbstractDataFrame,
+        cols::Union{ColumnIndex, AbstractVector, Regex, Not, Colon}=:)
+
+Create a new `DataFrame` in which columns `cols` of data frame `df` are converted
```
Comment (nalimilan) [inline src/abstractdataframe/abstractdataframe.jl]:
```suggestion
Return a copy of data frame `df` with columns `cols` converted
```

File: src/abstractdataframe/abstractdataframe.jl [hunk 2]
```diff
@@ -1280,3 +1283,168 @@ julia> ncol(df)
...
+2×1 DataFrame
+│ Row │ a     │
+│     │ Int64 │
+├─────┼───────┤
+│ 1   │ 1     │
+│ 2   │ 2     │
+```
+"""
+function Missings.disallowmissing(df::AbstractDataFrame,
+                         cols::Union{ColumnIndex, AbstractVector, Regex, Not, Colon}=:)
```
Comment (nalimilan) [inline src/abstractdataframe/abstractdataframe.jl]: Wrong indentation. Same below.

File: src/abstractdataframe/abstractdataframe.jl [hunk 3]
```diff
@@ -1280,3 +1283,168 @@ julia> ncol(df)
...
+    idxcols = Set(index(df)[cols])
```
Comment (nalimilan) [inline src/abstractdataframe/abstractdataframe.jl]: Why not this?
```suggestion
    idxcols = unique!(index(df)[cols])
```

File: src/abstractdataframe/abstractdataframe.jl [hunk 4]
```diff
@@ -1280,3 +1283,168 @@ julia> ncol(df)
...
+        end
+    end
+    DataFrame(newcols, _names(df), copycols=false)
+end
+
+"""
+    allowmissing(df::AbstractDataFrame,
+        cols::Union{ColumnIndex, AbstractVector, Regex, Not, Colon}=:)
+
+Create a new `DataFrame` in which columns `cols` of data frame `df` are converted
```
Comment (nalimilan) [inline src/abstractdataframe/abstractdataframe.jl]:
```suggestion
Return a copy of data frame `df` with columns `cols` converted
```

File: src/abstractdataframe/abstractdataframe.jl [hunk 5]
```diff
@@ -1280,3 +1283,168 @@ julia> ncol(df)
...
+    end
+    DataFrame(newcols, _names(df), copycols=false)
+end
+
+"""
+    categorical(df::AbstractDataFrame,
+                cols::Union{ColumnIndex, AbstractVector, Regex, Not, Colon}=:;
+                compress::Bool=false)
+
+Create a new `DataFrame` and change columns selected by `cols` from `df`
```
Comment (nalimilan) [inline src/abstractdataframe/abstractdataframe.jl]:
```suggestion
Return a copy of data frame `df` with columns `cols` converted
```

File: src/abstractdataframe/abstractdataframe.jl [hunk 6]
```diff
@@ -1280,3 +1283,168 @@ julia> ncol(df)
...
+        else
+            push!(newcols, copy(x))
+        end
+    end
+    DataFrame(newcols, _names(df), copycols=false)
+end
+
+"""
+    categorical(df::AbstractDataFrame,
+                cols::Union{ColumnIndex, AbstractVector, Regex, Not, Colon}=:;
```
Comment (nalimilan) [inline src/abstractdataframe/abstractdataframe.jl]: This isn't completely correct, since passing `:` explicitly gives a different result. Maybe (in another PR) we should change that, and require people to pass `categorical(df, String)` or `categorical(df, Union{Missing,String})` explicitly to get the current behavior?

File: src/abstractdataframe/abstractdataframe.jl (hunk 3 above)
Comment (bkamins) [reply src/abstractdataframe/abstractdataframe.jl]: `Set` will be faster later (we repeatedly do `i in idxcols` check) and `unique!` will fail if `cols` is a `ColumnIndex` (a single column selector not wrapped in a vector)

File: src/abstractdataframe/abstractdataframe.jl [hunk 7]
```diff
@@ -1280,3 +1283,168 @@ julia> ncol(df)
 
 """
 (nrow, ncol)
+
+"""
+    disallowmissing(df::AbstractDataFrame,
+        cols::Union{ColumnIndex, AbstractVector, Regex, Not, Colon}=:)
```
[the remark this answers is not in the document]
Comment (bkamins) [reply src/abstractdataframe/abstractdataframe.jl]: fixed (I thought to use 4 spaces, but you are right)

File: src/abstractdataframe/abstractdataframe.jl (hunk 2 above)
Comment (bkamins) [reply src/abstractdataframe/abstractdataframe.jl]: fixed

File: src/abstractdataframe/abstractdataframe.jl (hunk 6 above)
Comment (bkamins) [reply src/abstractdataframe/abstractdataframe.jl]: I have fixed the docs to make it clearer (and I intentionally put the difference between `:` and no argument in the Examples section earlier).

Now the question is if we find the behavior of `categorical(df)` useful. I find it OK (i.e. when doing e.g. GLM later this is what you want to do) so I think we can leave it as is. But I guess it was you who created the initial implementation - right - so I do not want to override your intentions here 😄.

If we found `categorical(df)` unwanted (as you suggest) then I would add a deprecation warning in this PR and add a keyword argument that would allow the user to specify which types should be converted (but I think it is too complex - almost no one would use it, and the default behavior that we currently have seems to fit 95% of cases and if someone wants something else one simply will pass a list of columns t convert).

**Comment by bkamins** [comment]
@nalimilan - thank you for having a look at this PR.

File: src/abstractdataframe/abstractdataframe.jl (hunk 6 above)
Comment (nalimilan) [reply src/abstractdataframe/abstractdataframe.jl]: Fine with me. But better not show `cols=:`, and list two signatures instead, otherwise it's really misleading (the real value would be `[eltype(col) <: Union{AbstractString, Missing} for col in eachcol(df)]`).

File: src/abstractdataframe/abstractdataframe.jl (hunk 2 above)
Comment (nalimilan) [reply src/abstractdataframe/abstractdataframe.jl]: Still not AFAICT?

File: src/abstractdataframe/abstractdataframe.jl (hunk 6 above)
Comment (bkamins) [reply src/abstractdataframe/abstractdataframe.jl]: This is exactly what I did (see the PR after I pushed).

**Comment by bkamins** [comment]
Now it should be good - but please kindly have a look (sorry for the mess).

**Comment by bkamins** [comment]
OK - I will merge it when CI passes and I go through it without noticing anything.
