### PR TITLE
Fix `@spawn_or_run_task` with interactive threads

### LINKED ISSUE #3383: Tests of `describe` and `multithreading`  fail in Julia-1.10.0-beta3
[versioninfo](https://gist.github.com/George9000/32ef6bf3ff1dbb86267fb33104da7fe6)

tested with `ENV["JULIA_USE_FLISP_PARSER"] = 1` and with JuliaSyntax parser

saw similar errors in Julia 1.11.0-DEV.582 (a4562e608f)

<details>
<summary>describe failures</summary>

```
describe: Test Failed at /Users/foo/.julia/packages/DataFrames/58MUJ/test/dataframe.jl:571
  Expression: describe_output[:, [:variable; default_fields]] == describe(df)
   Evaluated: 6×7 DataFrame
 Row │ variable        mean    min         median      max         nmissing  e ⋯
     │ Symbol          Union…  Any         Any         Any         Int64     T ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ number          2.5     1.0         2.5         4.0                0  I ⋯
   2 │ number_missing  2.0     1.0         2.0         3.0                1  U
   3 │ string                  a                       d                  0  S
   4 │ string_missing          a                       c                  1  U
   5 │ dates                   2000-01-01  2002-01-01  2004-01-01         0  D ⋯
   6 │ catarray                1                       2                  0  C
                                                                1 column omitted == 6×7 DataFrame
 Row │ variable        mean    min         median  max         nmissing  eltyp ⋯
     │ Symbol          Union…  Any         Union…  Any         Int64     Type  ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ number          2.5     1           2.5     4                  0  Int64 ⋯
   2 │ number_missing  2.0     1           2.0     3                  1  Union
   3 │ string                  a                   d                  0  Strin
   4 │ string_missing          a                   c                  1  Union
   5 │ dates                   2000-01-01          2004-01-01         0  Date  ⋯
   6 │ catarray                1                   2                  0  Categ
                                                                1 column omitted

Stacktrace:
 [1] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/DataFrames/58MUJ/test/dataframe.jl:571 [inlined]
 [3] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [4] top-level scope
   @ ~/.julia/packages/DataFrames/58MUJ/test/dataframe.jl:541

describe: Test Failed at /Users/foo/.julia/packages/DataFrames/58MUJ/test/dataframe.jl:577
  Expression: describe_output ≅ describe(df, :all)
   Evaluated: 6×16 DataFrame
 Row │ variable        mean    std      min         q25     median      q75    ⋯
     │ Symbol          Union…  Union…   Any         Union…  Any         Union… ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ number          2.5     1.29099  1.0         1.75    2.5         3.25   ⋯
   2 │ number_missing  2.0     1.0      1.0         1.5     2.0         2.5
   3 │ string                           a
   4 │ string_missing                   a
   5 │ dates                            2000-01-01          2002-01-01         ⋯
   6 │ catarray                         1
                                                               9 columns omitted ≅ 6×16 DataFrame
 Row │ variable        mean    std      min         q25     median  q75     ma ⋯
     │ Symbol          Union…  Union…   Any         Union…  Union…  Union…  An ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ number          2.5     1.29099  1           1.75    2.5     3.25    4  ⋯
   2 │ number_missing  2.0     1.0      1           1.5     2.0     2.5     3
   3 │ string                           a                                   d
   4 │ string_missing                   a                                   c
   5 │ dates                            2000-01-01                          20 ⋯
   6 │ catarray                         1                                   2
                                                               9 columns omitted

Stacktrace:
 [1] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/DataFrames/58MUJ/test/dataframe.jl:577 [inlined]
 [3] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [4] top-level scope
   @ ~/.julia/packages/DataFrames/58MUJ/test/dataframe.jl:541

describe: Test Failed at /Users/foo/.julia/packages/DataFrames/58MUJ/test/dataframe.jl:580
  Expression: describe_output[:, [:variable, :mean, :std, :min, :q25, :median, :q75, :max, :nunique, :nmissing, :eltype]] ≅ describe(df, :detailed)
   Evaluated: 6×11 DataFrame
 Row │ variable        mean    std      min         q25     median      q75    ⋯
     │ Symbol          Union…  Union…   Any         Union…  Any         Union… ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ number          2.5     1.29099  1.0         1.75    2.5         3.25   ⋯
   2 │ number_missing  2.0     1.0      1.0         1.5     2.0         2.5
   3 │ string                           a
   4 │ string_missing                   a
   5 │ dates                            2000-01-01          2002-01-01         ⋯
   6 │ catarray                         1
                                                               4 columns omitted ≅ 6×11 DataFrame
 Row │ variable        mean    std      min         q25     median  q75     ma ⋯
     │ Symbol          Union…  Union…   Any         Union…  Union…  Union…  An ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ number          2.5     1.29099  1           1.75    2.5     3.25    4  ⋯
   2 │ number_missing  2.0     1.0      1           1.5     2.0     2.5     3
   3 │ string                           a                                   d
   4 │ string_missing                   a                                   c
   5 │ dates                            2000-01-01                          20 ⋯
   6 │ catarray                         1                                   2
                                                               4 columns omitted

Stacktrace:
 [1] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/DataFrames/58MUJ/test/dataframe.jl:580 [inlined]
 [3] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [4] top-level scope
   @ ~/.julia/packages/DataFrames/58MUJ/test/dataframe.jl:541
Test Summary: | Pass  Fail  Total  Time
describe      |   13     3     16  2.2s
        FAILED: dataframe.jl
LoadError: Some tests did not pass: 13 passed, 3 failed, 0 errored, 0 broken.
in expression starting at /Users/foo/.julia/packages/DataFrames/58MUJ/test/dataframe.jl:1
```
  
</details>

<details>
<summary>multithreading disable failures</summary>

```
disabling multithreading via keyword argument: Test Failed at /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:157
  Expression: combine(gd, [] => ((()->begin
                        #= /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:157 =#
                        Threads.threadid()
                    end) => :id1), [] => ((()->begin
                        #= /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:158 =#
                        Threads.threadid()
                    end) => :id2), threads = true) != DataFrame(y = 1:4, id1 = 1, id2 = 1)
   Evaluated: 4×3 DataFrame
 Row │ y      id1    id2
     │ Int64  Int64  Int64
─────┼─────────────────────
   1 │     1      1      1
   2 │     2      1      1
   3 │     3      1      1
   4 │     4      1      1 != 4×3 DataFrame
 Row │ y      id1    id2
     │ Int64  Int64  Int64
─────┼─────────────────────
   1 │     1      1      1
   2 │     2      1      1
   3 │     3      1      1
   4 │     4      1      1

Stacktrace:
 [1] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:157 [inlined]
 [3] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [4] top-level scope
   @ ~/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:80

disabling multithreading via keyword argument: Test Failed at /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:177
  Expression: select(gd, [] => ((()->begin
                        #= /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:177 =#
                        Threads.threadid()
                    end) => :id1), [] => ((()->begin
                        #= /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:178 =#
                        Threads.threadid()
                    end) => :id2), threads = true) != DataFrame(y = refdf.y, id1 = 1, id2 = 1)
   Evaluated: 1000×3 DataFrame
  Row │ y      id1    id2
      │ Int64  Int64  Int64
──────┼─────────────────────
    1 │     2      1      1
    2 │     3      1      1
    3 │     1      1      1
    4 │     4      1      1
    5 │     2      1      1
    6 │     2      1      1
    7 │     4      1      1
    8 │     4      1      1
  ⋮   │   ⋮      ⋮      ⋮
  994 │     4      1      1
  995 │     2      1      1
  996 │     4      1      1
  997 │     4      1      1
  998 │     1      1      1
  999 │     1      1      1
 1000 │     4      1      1
            985 rows omitted != 1000×3 DataFrame
  Row │ y      id1    id2
      │ Int64  Int64  Int64
──────┼─────────────────────
    1 │     2      1      1
    2 │     3      1      1
    3 │     1      1      1
    4 │     4      1      1
    5 │     2      1      1
    6 │     2      1      1
    7 │     4      1      1
    8 │     4      1      1
  ⋮   │   ⋮      ⋮      ⋮
  994 │     4      1      1
  995 │     2      1      1
  996 │     4      1      1
  997 │     4      1      1
  998 │     1      1      1
  999 │     1      1      1
 1000 │     4      1      1
            985 rows omitted

Stacktrace:
 [1] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:177 [inlined]
 [3] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [4] top-level scope
   @ ~/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:80

disabling multithreading via keyword argument: Test Failed at /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:181
  Expression: select!(gd, [] => ((()->begin
                        #= /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:181 =#
                        Threads.threadid()
                    end) => :id1), [] => ((()->begin
                        #= /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:182 =#
                        Threads.threadid()
                    end) => :id2), threads = true) != DataFrame(y = refdf.y, id1 = 1, id2 = 1)
   Evaluated: 1000×3 DataFrame
  Row │ y      id1    id2
      │ Int64  Int64  Int64
──────┼─────────────────────
    1 │     2      1      1
    2 │     3      1      1
    3 │     1      1      1
    4 │     4      1      1
    5 │     2      1      1
    6 │     2      1      1
    7 │     4      1      1
    8 │     4      1      1
  ⋮   │   ⋮      ⋮      ⋮
  994 │     4      1      1
  995 │     2      1      1
  996 │     4      1      1
  997 │     4      1      1
  998 │     1      1      1
  999 │     1      1      1
 1000 │     4      1      1
            985 rows omitted != 1000×3 DataFrame
  Row │ y      id1    id2
      │ Int64  Int64  Int64
──────┼─────────────────────
    1 │     2      1      1
    2 │     3      1      1
    3 │     1      1      1
    4 │     4      1      1
    5 │     2      1      1
    6 │     2      1      1
    7 │     4      1      1
    8 │     4      1      1
  ⋮   │   ⋮      ⋮      ⋮
  994 │     4      1      1
  995 │     2      1      1
  996 │     4      1      1
  997 │     4      1      1
  998 │     1      1      1
  999 │     1      1      1
 1000 │     4      1      1
            985 rows omitted

Stacktrace:
 [1] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:181 [inlined]
 [3] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [4] top-level scope
   @ ~/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:80

disabling multithreading via keyword argument: Test Failed at /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:201
  Expression: transform(gd, [] => ((()->begin
                        #= /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:201 =#
                        Threads.threadid()
                    end) => :id1), [] => ((()->begin
                        #= /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:202 =#
                        Threads.threadid()
                    end) => :id2), threads = true) != [refdf DataFrame(id1 = fill(1, nrow(refdf)), id2 = 1)]
   Evaluated: 1000×4 DataFrame
  Row │ x      y      id1    id2
      │ Int64  Int64  Int64  Int64
──────┼────────────────────────────
    1 │     1      2      1      1
    2 │     2      3      1      1
    3 │     3      1      1      1
    4 │     4      4      1      1
    5 │     5      2      1      1
    6 │     6      2      1      1
    7 │     7      4      1      1
    8 │     8      4      1      1
  ⋮   │   ⋮      ⋮      ⋮      ⋮
  994 │   994      4      1      1
  995 │   995      2      1      1
  996 │   996      4      1      1
  997 │   997      4      1      1
  998 │   998      1      1      1
  999 │   999      1      1      1
 1000 │  1000      4      1      1
                   985 rows omitted != 1000×4 DataFrame
  Row │ x      y      id1    id2
      │ Int64  Int64  Int64  Int64
──────┼────────────────────────────
    1 │     1      2      1      1
    2 │     2      3      1      1
    3 │     3      1      1      1
    4 │     4      4      1      1
    5 │     5      2      1      1
    6 │     6      2      1      1
    7 │     7      4      1      1
    8 │     8      4      1      1
  ⋮   │   ⋮      ⋮      ⋮      ⋮
  994 │   994      4      1      1
  995 │   995      2      1      1
  996 │   996      4      1      1
  997 │   997      4      1      1
  998 │   998      1      1      1
  999 │   999      1      1      1
 1000 │  1000      4      1      1
                   985 rows omitted

Stacktrace:
 [1] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:201 [inlined]
 [3] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [4] top-level scope
   @ ~/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:80

disabling multithreading via keyword argument: Test Failed at /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:205
  Expression: transform!(gd, [] => ((()->begin
                        #= /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:205 =#
                        Threads.threadid()
                    end) => :id1), [] => ((()->begin
                        #= /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:206 =#
                        Threads.threadid()
                    end) => :id2), threads = true) != [refdf DataFrame(id1 = fill(1, nrow(refdf)), id2 = 1)]
   Evaluated: 1000×4 DataFrame
  Row │ x      y      id1    id2
      │ Int64  Int64  Int64  Int64
──────┼────────────────────────────
    1 │     1      2      1      1
    2 │     2      3      1      1
    3 │     3      1      1      1
    4 │     4      4      1      1
    5 │     5      2      1      1
    6 │     6      2      1      1
    7 │     7      4      1      1
    8 │     8      4      1      1
  ⋮   │   ⋮      ⋮      ⋮      ⋮
  994 │   994      4      1      1
  995 │   995      2      1      1
  996 │   996      4      1      1
  997 │   997      4      1      1
  998 │   998      1      1      1
  999 │   999      1      1      1
 1000 │  1000      4      1      1
                   985 rows omitted != 1000×4 DataFrame
  Row │ x      y      id1    id2
      │ Int64  Int64  Int64  Int64
──────┼────────────────────────────
    1 │     1      2      1      1
    2 │     2      3      1      1
    3 │     3      1      1      1
    4 │     4      4      1      1
    5 │     5      2      1      1
    6 │     6      2      1      1
    7 │     7      4      1      1
    8 │     8      4      1      1
  ⋮   │   ⋮      ⋮      ⋮      ⋮
  994 │   994      4      1      1
  995 │   995      2      1      1
  996 │   996      4      1      1
  997 │   997      4      1      1
  998 │   998      1      1      1
  999 │   999      1      1      1
 1000 │  1000      4      1      1
                   985 rows omitted

Stacktrace:
 [1] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:205 [inlined]
 [3] macro expansion
   @ ~/applications/juliadev/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [4] top-level scope
   @ ~/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:80
Test Summary:                                 | Pass  Fail  Total  Time
disabling multithreading via keyword argument |   15     5     20  4.1s
        FAILED: multithreading.jl
LoadError: Some tests did not pass: 15 passed, 5 failed, 0 errored, 0 broken.
in expression starting at /Users/foo/.julia/packages/DataFrames/58MUJ/test/multithreading.jl:1
```
  
</details>

### PR DESCRIPTION
**Pull request by nalimilan**
When Julia ≥ 1.9 is started with `-tX,Y`, by default tasks use the pool of interactive threads instead of the default pool. Fix this by updating `spawn_or_run_task` to match the code used by `@spawn` in Julia master.

Fixes #3383.

### CODE REVIEW

File: src/other/utils.jl [hunk 1]
```diff
@@ -221,16 +221,22 @@ end
...
 otherwise run `expr` and return a `Task` that returns its value.
 """
-macro spawn_or_run_task(threads, expr)
-    letargs = Base._lift_one_interp!(expr)
+macro spawn_or_run_task(threads, ex)
+    letargs = Base._lift_one_interp!(ex)
 
-    thunk = esc(:(()->($expr)))
+    thunk = :(()->($(esc(ex))))
+    @static if VERSION >= v"1.10.0-DEV"
```
Comment (bkamins) [inline src/other/utils.jl:228]: why `@static` here?

File: src/other/utils.jl [hunk 2]
```diff
@@ -221,16 +221,22 @@ end
...
+        Base.replace_linenums!(thunk, __source__)
```
Comment (bkamins) [inline src/other/utils.jl:229]: I understand we do not need `thunk = Base.replace_linenums!(thunk, __source__)`?

**Comment by bkamins** [comment]
Do we also need to update `macro spawn_or_run(threads, expr)`?

**Comment by bkamins** [comment]
And also maybe we should add to documentation that we spawn threads in `:default` mode?

File: src/other/utils.jl (hunk 1 above)
Comment (nalimilan) [reply src/other/utils.jl:228]: I tend to always use it for version checks (other than in global scope) since [that ensures the branch is eliminated at parse time](https://stackoverflow.com/a/65740489/2413179). But in this case since it's a macro I'm not sure it makes a difference. Maybe I'm being overzealous. I can drop that if you prefer -- or conversely use it with the other check for consistency.

File: src/other/utils.jl (hunk 2 above)
Comment (nalimilan) [reply src/other/utils.jl:229]: I'm not sure what this does but I assume this improves line number in stacktraces?

**Comment by nalimilan** [comment]
What do you think about setting `JULIA_NUM_THREADS=4,1` for tests? Interestingly, this appears to be accepted by Julia 1.6.5, giving 4 threads (it seems anything after the digit is ignored).

**Comment by bkamins** [comment]
> What do you think about setting JULIA_NUM_THREADS=4,1 for tests?

OK

File: src/other/utils.jl (hunk 1 above)
Comment (bkamins) [reply src/other/utils.jl:228]: This is the reason I asked - it is there in one place but not in the other. I would assume that `@static` is not needed, but I asked on Slack.

File: src/other/utils.jl (hunk 2 above)
Comment (bkamins) [reply src/other/utils.jl:229]: No - I meant the `thunk =` part, i.e. does `Base.replace_linenums!` guarantee to update `thunk` in place?

Comment (nalimilan) [reply src/other/utils.jl:229]: Ah good point. Yes, it always returns `thunk`.

File: src/other/utils.jl [hunk 3]
```diff
@@ -221,16 +221,23 @@ end
...
     var = esc(Base.sync_varname)
+    spawn_set_thrpool = VERSION >= v"1.9.0" ?
+        :(Base.Threads._spawn_set_thrpool(task, :default)) :
+        :()
     quote
         let $(letargs...)
             if $(esc(threads))
                 local task = Task($thunk)
                 task.sticky = false
+                $(spawn_set_thrpool)
```
Comment (bkamins) [inline src/other/utils.jl:240]: Just to be 100% sure. Is the macro hygiene here correct? I.e. the `task` variable will be left untouched in the interpolated expression and refer to the local `task` from line 238?.

Comment (nalimilan) [reply src/other/utils.jl:240]: AFAIK local variables names are only replaced with `gensym` as a final step once the macro has returned an expression, so it doesn't make a difference whether we build the expression in multiple steps. What makes me confident that it's the case is that tests pass. ;-)

**Comment by bkamins** [comment]
Looks good. Do you think we should additionally ask someone more who knows threading internals for review?

**Comment by bkamins** [comment]
OK - so I think it is safe to merge this once you are ready :).
Maybe one small thing - can you also please add a NEWS.md entry for this?

**Review by bkamins — APPROVED** [review]
